name: Lefine
description: Widget for Lefine

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # STORY BOOK
  widgetbook: ^2.4.1
  # CONTEXT
  kartal: ^2.7.0
  # STATE MANAGEMENT
  flutter_riverpod: ^2.1.3
  # CACHE
  shared_preferences: ^2.0.15
  # SVG
  flutter_svg: ^1.1.6
  # RESPONSIVE
  responsive_builder: ^0.4.3
  # LOCALIZATION
  easy_localization: ^3.0.0
  # ANALYZER
  very_good_analysis: ^3.1.0
  # ANIMATIONS
  rive: ^0.10.0
  #COLORS
  tailwind_colors: ^0.3.1
  #UIKIT
  lefine_theme:
    git: https://github.com/yurrpt/lefine_theme.git
  uikit:
    path: module/uikit
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  fonts:
    enabled: true

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

dev_dependencies:
  integration_test:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/
